## Basics

In [180]:
import numpy as np
import pandas as pd


In [181]:
falsy_value=(0,False,None,{},[],'') # All are falsy value in python.

In [182]:
any(falsy_value)

False

In [183]:
np.nan #nan-->Not A Number

nan

In [184]:
3+np.nan

nan

In [185]:
a=np.array([1,2,np.nan,np.nan,4]) #The np.nan value is kind of a virus. Everything that it touches becomes np.nan

In [186]:
a.sum()

np.float64(nan)

In [187]:
np.inf #This also behave like a virus.

inf

In [188]:
3+np.inf

inf

In [189]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [190]:
b.sum() #If there are both nan and inf then priority is always nan.

np.float64(nan)

In [191]:
np.isnan(np.nan) #Checking 

np.True_

In [192]:
np.isinf(np.inf) #Checking

np.True_

In [193]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False,  True, False, False])

In [194]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False, False,  True, False])

In [195]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

In [196]:
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [197]:
b[np.isfinite(b)]

array([1., 2., 3., 4.])

In [198]:
b[~np.isfinite(b)].sum()

np.float64(nan)

## Pandas utility functions
#### Similarly to numpy, pandas also has a few utility functions to identify and detect null values

In [199]:
pd.isnull(np.nan)

True

In [200]:
pd.notnull(np.nan)

False

#### This also works for series and data frame.

In [201]:
pd.isnull(pd.Series([1,3,None,'A']))

0    False
1    False
2     True
3    False
dtype: bool

In [202]:
pd.isnull(pd.DataFrame( #This do not tell the sum, this show how many number are null in column3.
    {
        'Column1':[1,2,3],
        'Column2':[3,4,np.nan],
        'Column3':[np.nan,5,np.nan]
    }))['Column3'].sum()

np.int64(2)

In [203]:
df=pd.isnull(pd.DataFrame( 
    {
        'Column1':[1,2,3],
        'Column2':[3,4,np.nan],
        'Column3':[np.nan,5,np.nan]
    }))
df

,Column1,Column2,Column3
0,False,False,True
1,False,False,False
2,False,True,True


In [204]:

s = pd.Series([1, 2, 3, np.nan, np.nan, 4])

In [205]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [206]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [207]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [208]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64  
dtypes: float64(3), int64(1)
memory usage: 260.0 bytes


In [209]:
df.isnull()


,Column A,Column B,Column C,Column D
0,False,False,True,False
1,True,False,False,False
2,False,False,False,False
3,True,True,False,False


In [210]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [211]:
df.dropna(axis=0)

,Column A,Column B,Column C,Column D
2,30.0,31.0,32.0,34


In [212]:
df.dropna(axis=1)

,Column D
0,5
1,8
2,34
3,110


In [213]:
df2 = pd.DataFrame({
    'Column A': [2, np.nan, 30],
    'Column B': [np.nan, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [214]:
df2.dropna(how='all')#all works as or.

,Column A,Column B,Column C
0,2.0,NaN,NaN
2,30.0,31.0,100.0


In [215]:
df2.dropna(how='any')#any works as and.

,Column A,Column B,Column C
2,30.0,31.0,100.0


In [216]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [217]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [218]:
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [219]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [220]:
s.fillna(s.ffill())

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [221]:
s.fillna(s.bfill())

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [222]:
pd.Series([np.nan,3,2,np.nan]).ffill()

0    NaN
1    3.0
2    2.0
3    2.0
dtype: float64

In [223]:
df

,Column A,Column B,Column C,Column D
0,1.0,2.0,NaN,5
1,NaN,8.0,9.0,8
2,30.0,31.0,32.0,34
3,NaN,NaN,100.0,110


In [224]:
df.fillna({
    'Column A':0,'Column B':69,'Column C':df['Column C'].mean()
})

,Column A,Column B,Column C,Column D
0,1.0,2.0,47.0,5
1,0.0,8.0,9.0,8
2,30.0,31.0,32.0,34
3,0.0,69.0,100.0,110


In [225]:
df.ffill(axis=1)


,Column A,Column B,Column C,Column D
0,1.0,2.0,2.0,5.0
1,NaN,8.0,9.0,8.0
2,30.0,31.0,32.0,34.0
3,NaN,NaN,100.0,110.0


In [226]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [227]:
s.dropna().count()

np.int64(4)

In [228]:
missing_values=len(s.dropna())!=len(s)
missing_values

True

In [229]:
len(s)

6

In [230]:
s.count()

np.int64(4)

In [231]:
pd.Series([True, False, False]).all()

np.False_

In [232]:
pd.Series([True, False, False]).any()

np.True_

In [233]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [234]:
s.isnull().sum()

np.int64(2)

In [235]:
pd.Series([22,np.nan]).isnull().any()

np.True_

In [236]:
s.isnull().values

array([False, False, False,  True,  True, False])

In [237]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

,Sex,Age
0,M,29
1,F,30
2,F,24
3,D,290
4,?,25


In [238]:
df['Sex'].unique()

<StringArray>
['M', 'F', 'D', '?']
Length: 4, dtype: str

In [239]:
df['Sex'].value_counts()

Sex
F    2
M    1
D    1
?    1
Name: count, dtype: int64

In [240]:
df['Sex'].replace('D','F')

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: str

In [241]:
df['Sex'].replace({'D':'F','N':'M'})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: str

In [242]:
df.replace({
    'Sex':{
        'D':'F',
        'N':'M'
    },
    'Age':{
        290:29
    }
})

,Sex,Age
0,M,29
1,F,30
2,F,24
3,F,29
4,?,25


In [243]:
df[df['Age']>100]

,Sex,Age
3,D,290


In [244]:
df.loc[df['Age']>100,'Age']=df.loc[df['Age']>100,'Age']/10
df

,Sex,Age
0,M,29
1,F,30
2,F,24
3,D,29
4,?,25


## Dplicates

In [245]:

ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])

In [246]:
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: str

In [247]:
ambassadors.duplicated()

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [248]:
ambassadors.duplicated(keep='last')

Gérard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [249]:
ambassadors.duplicated(keep=False)

Gérard Araud          False
Kim Darroch            True
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [250]:
ambassadors.drop_duplicates()

Gérard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: str

In [251]:
ambassadors.drop_duplicates(keep='last')

Gérard Araud                  France
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Klaus Scharioth              Germany
dtype: str

In [252]:
ambassadors.drop_duplicates(keep=False)

Gérard Araud          France
Armando Varricchio     Italy
dtype: str

In [253]:
players = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos': [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})

In [254]:
players

,Name,Pos
0,Kobe Bryant,SG
1,LeBron James,SF
2,Kobe Bryant,SG
3,Carmelo Anthony,SF
4,Kobe Bryant,SF


In [255]:
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [256]:
players.drop_duplicates()

,Name,Pos
0,Kobe Bryant,SG
1,LeBron James,SF
3,Carmelo Anthony,SF
4,Kobe Bryant,SF


In [257]:
players.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [258]:
players.duplicated(subset='Name',keep='last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [259]:
players.drop_duplicates(subset='Name')

,Name,Pos
0,Kobe Bryant,SG
1,LeBron James,SF
3,Carmelo Anthony,SF


In [260]:
players.drop_duplicates(subset='Name' ,keep='last')


,Name,Pos
1,LeBron James,SF
3,Carmelo Anthony,SF
4,Kobe Bryant,SF


In [261]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})

In [262]:
df

,Data
0,1987_M_US _1
1,1990?_M_UK_1
2,1992_F_US_2
3,1970?_M_ IT_1
4,1985_F_I T_2


In [263]:
df['Data'].str.split('_')

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [264]:
df=df['Data'].str.split('_',expand=True)

In [265]:
df.columns=['Year','Sex','Country','No.children']

In [266]:
df

,Year,Sex,Country,No.children
0,1987,M,US,1
1,1990?,M,UK,1
2,1992,F,US,2
3,1970?,M,IT,1
4,1985,F,I T,2


In [267]:
df['Year'].str.contains(r'\?')      #r-->raw string

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool

In [268]:
df['Country'].str.replace(' ','')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: str