# Basics

In [1]:
import sys
import numpy as np

In [2]:
a=np.array([12,13,65,76])
b=np.array([2.4,5.4,6,8.7])
a[0],a[1]
a[1:4]

array([13, 65, 76])

# Array Basic

In [3]:
a=np.array([12,13,65,76])
a[1:-1]
a[::2]

array([12, 65])

In [4]:
b
b[[1,2,3]],b[1],b[-1]

(array([5.4, 6. , 8.7]), np.float64(5.4), np.float64(8.7))

In [5]:
a.dtype


dtype('int64')

In [6]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [7]:
c=np.array(['a','b','c'])
c.dtype

dtype('<U1')

In [8]:
d=np.array([{'a':1},sys])
d.dtype

dtype('O')

# Dimensions and shapes


In [9]:
A=np.array([
    [1,2,3],
    [4,5,6]
])
A.shape

(2, 3)

In [10]:
A.ndim

2

In [11]:
A.size

6

In [12]:
B=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
B.shape

(2, 2, 3)

In [13]:

B.ndim

3

In [14]:
B.size

12

In [15]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
B.dtype

dtype('int64')

# Indexing And Slicing Of Matrices 


In [17]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A[1]

array([4, 5, 6])

In [18]:
A[1][0]

np.int64(4)

In [19]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
A[:2,2:]

array([[3],
       [6]])

In [22]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
A[2]=22
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [22, 22, 22]])

In [24]:
A[2,0]=7
A[2,1]=8
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 22]])

# Statistics

In [25]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [26]:

a.mean()

np.float64(2.5)

In [27]:
a.std()

np.float64(1.118033988749895)

In [28]:
a.var()

np.float64(1.25)

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.sum()

np.int64(45)

In [30]:
A.mean()


np.float64(5.0)

In [31]:
A.std()

np.float64(2.581988897471611)

In [32]:
A.var()

np.float64(6.666666666666667)

In [33]:
A.sum(axis=1)

array([ 6, 15, 24])

In [34]:
A.sum(axis=0)

array([12, 15, 18])

# Operations


In [35]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [36]:
a+10


array([10, 11, 12, 13])

In [37]:
a*10

array([ 0, 10, 20, 30])

In [38]:
a+=100
a

array([100, 101, 102, 103])

In [39]:
a

array([100, 101, 102, 103])

In [40]:
l=[1,2,3,4]
[i*2 for i in l]

[2, 4, 6, 8]

In [41]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [42]:
b=np.array([10,10,10,10])
b

array([10, 10, 10, 10])

In [43]:
a+b


array([10, 11, 12, 13])

In [44]:
c=a/b 
c,c.dtype

(array([0. , 0.1, 0.2, 0.3]), dtype('float64'))

# Boolean Operations 

In [45]:
a=np.array([10,11,12,13])
a

array([10, 11, 12, 13])

In [46]:
a[[0,1,-1]]

array([10, 11, 13])

In [47]:
a[[True,False,True,True]]

array([10, 12, 13])

In [48]:
a

array([10, 11, 12, 13])

In [49]:
a>=12

array([False, False,  True,  True])

In [50]:
a[a>=12]

array([12, 13])

In [51]:
a[a>a.mean()]

array([12, 13])

In [52]:
a[~(a>a.mean())]

array([10, 11])

In [53]:
a[(a==12) | (a==11)]

array([11, 12])

In [54]:
A=np.random.randint(100,size=(3,3))
A

array([[62, 48, 22],
       [95,  8, 90],
       [80, 17, 16]], dtype=int32)

In [55]:
A>30

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False, False]])

In [56]:
A[A>30]

array([62, 48, 95, 90, 80], dtype=int32)

# Linear Algebra

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
B=np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [59]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [60]:
A@B

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [61]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
sys.getsizeof(1)

28

In [63]:
sys.getsizeof(10**100)

72

In [64]:
np.dtype(int).itemsize

8

In [65]:
np.dtype(np.int8).itemsize

1

In [66]:
np.dtype(float).itemsize

8

# Performance

In [67]:
l = list(range(100000))
a = np.arange(100000)
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1.38 ms


np.int64(333328333350000)

In [68]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 7.34 ms


333328333350000

# Some Useful functions


In [69]:
np.random.random(size=2)

array([0.53162328, 0.58074201])

In [70]:
np.random.normal(size=2)

array([0.23266504, 0.26876504])

In [71]:
np.random.rand(2,4)

array([[0.88127903, 0.05840165, 0.92413993, 0.30722718],
       [0.39673808, 0.36240845, 0.32636702, 0.83378109]])

In [72]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [73]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [74]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [75]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [78]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [79]:

np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [80]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
np.empty(5)


array([0., 0., 0., 0., 0.])

In [84]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])