# NumPy Mini Project
## IPL Team Performance Analysis[2025] (Using NumPy Only)

## Project Objective

### Analyze IPL team performance using NumPy arrays.

In [76]:
import numpy as np
team=np.array(["RCB","MI","KKR","SRH","CSK"])


#### Matches|Won|Loss|Run|Wicket

In [77]:
data=np.array([
    [14, 10, 4, 2357, 108], #RCB
    [14, 8, 6, 2472, 114], #MI
    [14, 7, 7, 1995, 88], #KKR
    [14, 7, 7, 2519, 92], #SRH
    [14, 4, 10, 2441, 85] #CSK
])

## 1. Basic Column Extraction

#### Extract Matches column

In [78]:
data[:,0]

array([14, 14, 14, 14, 14])

#### Extract Wins column

In [79]:
data[:,1]

array([10,  8,  7,  7,  4])

#### Extract Runs column

In [80]:
data[:,3]

array([2357, 2472, 1995, 2519, 2441])

### Extract Wicket column

In [81]:
data[:,4]

array([108, 114,  88,  92,  85])

## 2.Win Percentage Calculation

#### Win Percentage Calculation

In [82]:
(data[:,1]/data[:,0])*100

array([71.42857143, 57.14285714, 50.        , 50.        , 28.57142857])

#### Store it in a new array

In [83]:
win_percentage=np.round((data[:,1]/data[:,0])*100,2)
win_percentage

array([71.43, 57.14, 50.  , 50.  , 28.57])

## 3.Find Maximum Values

#### Team with maximum wins

In [84]:
max_idx=np.argmax(data[:,1])
print(f"{team[max_idx]}:{data[max_idx,1]}")


RCB:10


#### Team with maximum runs

In [85]:
max_idx=np.argmax(data[:,-2])
print(f"{team[max_idx]}:{data[max_idx,-2]}")


SRH:2519


#### Team with maximum wicket

In [86]:
max_idx=np.argmax(data[:,-1])
print(f"{team[max_idx]}:{data[max_idx,-1]}")

MI:114


## 4.Find Minimum Values

#### Team with minimum wins

In [87]:
idx_min=np.argmin(data[:,1])
print(f"{team[idx_min]}:{data[idx_min,1]}")

CSK:4


#### Team with minimum runs

In [88]:
idx_min=np.argmin(data[:,-2])
print(f"{team[idx_min]}:{data[idx_min,-2]}")

KKR:1995


## 5.Boolean Filtering

#### With win % greater than 50%

In [89]:
team[win_percentage>=50.0]

array(['RCB', 'MI', 'KKR', 'SRH'], dtype='<U3')

#### With runs greater than average

In [90]:
average_run=data[:,-2].mean()
team[data[:,-2]>average_run]

array(['RCB', 'MI', 'SRH', 'CSK'], dtype='<U3')

#### With wickets less than average

In [91]:
average_wicket=data[:,-1].mean()
team[data[:,-1]>average_wicket]

array(['RCB', 'MI'], dtype='<U3')

## 6.Broadcasting Operation

#### Add 10 runs to every team

In [92]:
data[:,-2]+=10
data

array([[  14,   10,    4, 2367,  108],
       [  14,    8,    6, 2482,  114],
       [  14,    7,    7, 2005,   88],
       [  14,    7,    7, 2529,   92],
       [  14,    4,   10, 2451,   85]])

#### Add 1 extra win to every team


In [93]:
data[:,1]+=1
data[:,2]-=1
data

array([[  14,   11,    3, 2367,  108],
       [  14,    9,    5, 2482,  114],
       [  14,    8,    6, 2005,   88],
       [  14,    8,    6, 2529,   92],
       [  14,    5,    9, 2451,   85]])

#### Recalculate win percentage

In [94]:
win_percentage_2=np.round((data[:,1]/data[:,0])*100,2)
win_percentage_2
                  

array([78.57, 64.29, 57.14, 57.14, 35.71])

## 7.Sorting

#### Sort teams based on wins

In [ ]:
idx=data[:,1].argsort()[::-1]
for i in idx:
    print(f"{team[i]}:{data[i,1]}")

RCB:11
MI:9
KKR:8
SRH:8
CSK:5


#### Sort teams based on runs

In [96]:
idx=data[:,-2].argsort()[::-1]
for i in idx:
    print(f"{team[i]}:{data[i,-2]}")

SRH:2529
MI:2482
CSK:2451
RCB:2367
KKR:2005


## 8.Ranking Logic

#### Wins (highest first)


In [97]:
idx=data[:,1].argsort()[::-1]
team[idx]

array(['RCB', 'MI', 'KKR', 'SRH', 'CSK'], dtype='<U3')

## 9.Conditional Check

#### If any team has win % above 70%

In [98]:
team[win_percentage_2>70]

array(['RCB'], dtype='<U3')

#### If any team lost more than they won

In [99]:
team[data[:,1]<data[:,2]]

array(['CSK'], dtype='<U3')