In [104]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'c:\\Users\\tongi\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\version.py'>


## Create a numpy array of size 10, filled with zeros.


In [105]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a numpy array with values ranging from 10 to 49

In [106]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create a numpy matrix of 2*2 integers, filled with ones.

In [107]:
np.ones([2,2],dtype=int) 

array([[1, 1],
       [1, 1]])

## Create a numpy matrix of 3*2 float numbers, filled with ones.


In [108]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [109]:
x=np.arange(4,dtype=int)
np.ones_like(x)

array([1, 1, 1, 1])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.


In [110]:
x=np.arange(4,dtype=int)
np.zeros_like(x)

array([0, 0, 0, 0])

## Create a numpy matrix of 4*4 integers, filled with fives.


In [111]:
np.ones([4,4],dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


In [112]:
x=np.array([
    [1,2],
    [3,4]
])
np.ones_like(x)*7

array([[7, 7],
       [7, 7]])

## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [113]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a numpy array, filled with 3 random integer values between 1 and 10.


In [114]:
np.random.randint(10,size=3)

array([0, 8, 3], dtype=int32)

## Create a 3*3*3 numpy matrix, filled with random float values.


In [115]:
np.random.randn(3,3,3)

array([[[ 1.23924882, -0.77104169,  0.39180978],
        [ 2.35682575, -0.22982917,  0.92004888],
        [-0.31778825,  0.69659308, -0.7767095 ]],

       [[ 0.55982594, -0.47149065, -1.77548028],
        [-0.60067339,  0.05511007, -1.78599609],
        [ 0.68364423,  1.15498388,  0.48919942]],

       [[-1.2157504 ,  0.70757522, -0.81428614],
        [-0.19318194,  0.61925807,  0.38883077],
        [-0.70531773,  1.75838567, -0.79661026]]])

## Given the X python list convert it to an Y numpy array

In [116]:
x=[1,2,3,4]
y=np.array(x)
y

array([1, 2, 3, 4])

## Given the X numpy array, make a copy and store it on Y.

In [117]:
x=np.arange(4)
print(x,id(x))
y=np.copy(x)
print(y,id(y))

[0 1 2 3] 2364078096720
[0 1 2 3] 2364078506512


## Create a numpy array with numbers from 1 to 10

In [118]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create a numpy array with the odd numbers between 1 to 10

In [119]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## Create a numpy array with numbers from 1 to 10, in descending order.

In [120]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [121]:

np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8


In [122]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Show the memory size of the given Z numpy matrix


In [123]:
z=np.arange(4)
print(z.size*z.itemsize)

32


## Given the X numpy array, show it's first element


In [124]:
x=np.array([1,2,3,4,54,5,5,54,3,232])
x[0]

np.int64(1)

## Given the X numpy array, show it's last element

In [125]:
x[-1]

np.int64(232)

## Given the X numpy array, show it's first three elements


In [126]:
x[0:3]

array([1, 2, 3])

## Given the X numpy array, show all middle elements

In [127]:
x[1:-1]

array([ 2,  3,  4, 54,  5,  5, 54,  3])

## Given the X numpy array, show the elements in reverse position

In [128]:
x[::-1] #Mirror

array([232,   3,  54,   5,   5,  54,   4,   3,   2,   1])

## Given the X numpy array, show the elements in an odd position


In [129]:
x[::2]

array([ 1,  3, 54,  5,  3])

## Given the X numpy matrix, show the first row elements

In [130]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x[0]

array([1, 2, 3])

## Given the X numpy matrix, show the last row elements

In [131]:
x[-1]

array([7, 8, 9])

## Given the X numpy matrix, show the first element on first row


In [132]:
x[0,0]

np.int64(1)

## Given the X numpy matrix, show the last element on last row


In [133]:
x[-1,-1]

np.int64(9)

## Given the X numpy matrix, show the middle row element.

In [134]:
x[1:-1,1:-1]

array([[5]])

## Given the X numpy matrix, show the first two elements on the first two rows

In [135]:
x[:2,:2]

array([[1, 2],
       [4, 5]])

## Given the X numpy matrix, show the last  elements on the last  rows

In [136]:
x[-2:,-2:]

array([[5, 6],
       [8, 9]])

## Convert the given integer numpy array to float

In [137]:
x=np.array([1,2,3,4],dtype=int)
x
np.array(x,dtype=float)

array([1., 2., 3., 4.])

## Reverse the given numpy array (first element becomes last)

In [138]:
a=np.array([81,9,6,76],dtype=int)
a[::-1]

array([76,  6,  9, 81])

## Order (sort) the given numpy array

In [139]:
a.sort()
a

array([ 6,  9, 76, 81])

## Given the X numpy array, set the second element equal to 1

In [140]:
a[1]=1
a

array([ 6,  1, 76, 81])

## Given the X numpy array, change the 6 with a 96

In [141]:
a[a==6]=96
a

array([96,  1, 76, 81])

## Given the X numpy matrix, change the last row with all 1

In [142]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x[-1]=1
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

## Given the X numpy matrix, change the last item on the last row with a 0

In [143]:
x[-1,-1]=0
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

## Given the X numpy matrix, add 5 to every element

In [144]:
x+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [ 6,  6,  5]])

## Given the X numpy array, make a mask showing negative elements


In [145]:
y=np.array([-1,6,5,-7,-9,6,2,9,-10,4,0])
mask=y<=0
mask

array([ True, False, False,  True,  True, False, False, False,  True,
       False,  True])

## Given the X numpy array, get the negative elements

In [146]:
y[mask]

array([ -1,  -7,  -9, -10,   0])

## Given the X numpy array, get numbers higher than 5

In [147]:
y[y>5]

array([6, 6, 9])

## Given the X numpy array, get numbers higher than the elements mean

In [148]:
y[y>y.mean()]

array([6, 5, 6, 2, 9, 4])

## Given the X numpy array, get numbers equal to 2 or 10


In [149]:
y[(y==2) |(y==10)]

array([2])

## Given the X numpy array, return True if none of its elements is zero

In [150]:
y.all()

np.False_

## Given the X numpy array, return True if any of its elements is zero

In [151]:
y.any()

np.True_

## Given the X numpy array, show the sum of its elements

In [152]:
y.sum()

np.int64(5)

## Given the X numpy array, show the mean value of its elements


In [153]:
y.mean()

np.float64(0.45454545454545453)

## Given the X numpy matrix, show the sum of its columns

In [154]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
x.sum(axis=0)

array([12, 15, 18])

## Given the X numpy matrix, show the mean value of its rows

In [155]:
x.mean(axis=1)

array([2., 5., 8.])

## Given the X numpy array, show the max value of its elements

In [156]:
x.max()

np.int64(9)